### PR TITLE
Redraw LineNumber after finishing setting up CodeView

### LINKED ISSUE #50: Linenumber color will not change if you don't focus on CodeView
First of all, this repo is very great!
I am now making a new editor for fun, when I am using CodeView, I found something strange.

If you don't focus on the CodeView widget, the Linenumber color will not change into the correct color scheme.

#### Before focus on
image
#### After focus on
image

> I think maybe LineNumber use `relief=flat` may look better

### PR DESCRIPTION
**Pull request by littlewhitecloud**
fix #50

### CODE REVIEW

**Comment by whmsft** [comment]
Looks good. Hope @rdbende finds time to review... Busy lad it seems

**Comment by littlewhitecloud** [comment]
Having a problem to set the justify of the line numbers by giving `justify="right"` to the codeview. It seems like the `Frame` doesn't have `justify` attribute.

Maybe we shouldn't do `super().__init__(**kwargs)`?

**Comment by Moosems** [comment]
What?

**Comment by littlewhitecloud** [comment]
image

**Comment by Moosems** [comment]
https://github.com/rdbende/chlorophyll/assets/95927277/0b1e4f90-6360-4946-b28f-7d39f6485070

**Comment by Moosems** [comment]
The start code was the exact code in the tklinenums doc. Maybe you need to uninstall and reinstall?

**Comment by littlewhitecloud** [comment]
lol my internet was bad and I can't receive that video.
But after reinstalling chlorophyll, it will still show the error. Maybe we should make a new publish and upgrade the version?

Moreover, I downloaded the latest version and it still shows the error.

**Comment by littlewhitecloud** [comment]
That's meaning the CodeView received a `justify` argument from the `**kwargs` but it doesn't have it, so it will raise an error.

**Comment by Moosems** [comment]
Reinstall tklinenums, not chlorophyll. It's a project dependency.

**Comment by Moosems** [comment]
This PR, however, looks good to me. Gonna merge.

**Comment by Moosems** [comment]
If you believe that the linenums package is broken, I'd make an issue there instead.

**Comment by littlewhitecloud** [comment]
Not the linenums package broken, I mean the problem is ```super().__init__(self, **kwargs)```

**Comment by littlewhitecloud** [comment]
My poor english maybe too bad, I will make an issue.

**Comment by Moosems** [comment]
Ah, just pop justify before the init

**Comment by Moosems** [comment]
I'll make a quick PR

**Pull request merged**
